version: '3'
services:
  slave1:
    image: "redis"
    ports:
     - "6379:6379"
    volumes:
     - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf 
  slave2:
    image: "redis"
    ports:
     - "6380:6379"
    volumes:
     - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf 
  slave3:
    image: "redis"
    ports:
     - "6381:6379"
    volumes:
     - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf 
  slave4:
    image: "redis"
    ports:
     - "6382:6379"
    volumes:
     - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf 
  slave5:
    image: "redis"
    ports:
     - "6383:6379"
    volumes:
     - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf 
  slave6:
    image: "redis"
    ports:
     - "6384:6379"
    volumes:
     - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf 